### ISSUE TITLE
Looking for templates\junit_viewer.js in current directory

### ISSUE THREAD

**Issue by scasagrande-d2l** [lukejpreston/junit_viewer#18]
**Version:** 
- junit-viewer@4.1.1
- node@5.0.0

**Setup:**
- Dummy folder named test located on my desktop with test.xml inside
- Install junit-viewer@4.1.1 globally
- In prompt, cd to desktop
- run `junit-viewer --results=test --port=9091`

**Results**

Copy of error:

```
Error: ENOENT: no such file or directory, open 'C:\Users\scasagrande\Desktop\templates\junit_viewer.js'
   at Error (native)
   at Object.fs.openSync (fs.js:584:18)
   at Object.fs.readFileSync (fs.js:431:33)
   at module.exports (C:\Users\scasagrande\AppData\Roaming\npm\node_modules\junit-viewer\render.js:68:83)
   at renderResults (C:\Users\scasagrande\AppData\Roaming\npm\node_modules\junit-viewer\index.js:26:12)
   at C:\Users\scasagrande\AppData\Roaming\npm\node_modules\junit-viewer\index.js:50:26
   at Layer.handle [as handle_request] (C:\Users\scasagrande\AppData\Roaming\npm\node_modules\junit-viewer\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\Users\scasagrande\AppData\Roaming\npm\node_modules\junit-viewer\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\Users\scasagrande\AppData\Roaming\npm\node_modules\junit-viewer\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (C:\Users\scasagrande\AppData\Roaming\npm\node_modules\junit-viewer\node_modules\express\lib\router\layer.js:95:5)
```

Seems to be looking for `templates\junit_viewer.js` in the current working directory. 

Problem non-existent in junit-viewer@3.3.2

**Expected Results**

- For it to load like it does in v3.3.2

**Comment by lukejpreston** [comment]
Could you try it again please version 4.3.0 should be working now

**Comment by scasagrande-d2l** [comment]
**Setup**
- Dummy folder named test located on my desktop with test.xml inside
- run `npm install -g junit-viewer@4.3.0`
- In prompt, cd to desktop
- run `junit-viewer --results=test --port=9091`

**Results**
```
PS C:\Users\scasagrande\Desktop> junit-viewer --results=test --port=9091
C:\Users\scasagrande\AppData\Roaming\npm\node_modules\junit-viewer\src\junit_viewer_cli.js:37
            var app = express()
                      ^

ReferenceError: express is not defined
    at Object.start (C:\Users\scasagrande\AppData\Roaming\npm\node_modules\junit-viewer\src\junit_viewer_cli.js:37:23)
    at Object.<anonymous> (C:\Users\scasagrande\AppData\Roaming\npm\node_modules\junit-viewer\bin\junit-viewer:3:39)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

Seems that express is not defined.

**Comment by lukejpreston** [comment]
I have fixed this in version 4.4.0, could you try that please

**Comment by scasagrande-d2l** [comment]
Seems to load now, thank you.

I will also point out though that when I launched `junit-viewer@4.4.0`, it spat back at me:

`Junit Viewer Listening at http://:::9091`

Missing any hostname. But the server is up and viewable, so its working now.

**Comment by lukejpreston** [comment]
I thought it might work but looks like it is possible different on MAC I will remove the console log but keep the port but I am going to close this ticket. Also you don't need to specify the port number if you don't want to, it will default to 9090 just run

```
junit-viewer --results=test --port
```
