### ISSUE TITLE
Error: ENOENT, no such file or directory 'test_data'

### ISSUE THREAD

**Issue by JeffML** [lukejpreston/junit_viewer#7]
Getting the above error when running with --folder, --save params

```bash
junit-viewer --folder=static/frisby/reports/release --save=static/frisby/reports/release/results.html
fs.js:792
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'test_data'
    at Error (native)
    at Object.fs.lstatSync (fs.js:792:18)
    at Object.<anonymous> (/opt/local/lib/node_modules/junit-viewer/index.js:27:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/local/lib/node_modules/junit-viewer/bin/junit-viewer:3:1)
```
contents of --folder dir:
```bash
jeff.l@Jeffs-MacBook-Pro:~/tests/TestReportServer (master *=)$ ls static/frisby/reports/release
TEST-FrisbyTestATTest_AssetTracker_specAssetTrackerselect.xml                                TEST-FrisbyTestATTest_Logo_specNoLogo.xml
TEST-FrisbyTestATTest_AssetTracker_specChooseAssetTrackerandverifymaterialisunselected.xml   TEST-FrisbyTestATTest_Logo_specstart.xml
TEST-FrisbyTestATTest_AssetTracker_specChoosemetal.xml                                       TEST-FrisbyTestATTest_maxcharsbydesign_specAssetTrackerDesign.xml
TEST-FrisbyTestATTest_AssetTracker_specSwitchbacktoSmall.xml                                 TEST-FrisbyTestATTest_maxcharsbydesign_specCustomAssetTagDesign.xml
TEST-FrisbyTestATTest_AssetTracker_specstart.xml                                             TEST-FrisbyTestATTest_maxcharsbydesign_specStandardAssetTagDesign.xml
TEST-FrisbyTestATTest_BCnumberinganddatamergeinterplay_specBarcodeNumberOnly.xml             TEST-FrisbyTestATTest_maxcharsbydesign_specstart.xml
TEST-FrisbyTestATTest_BCnumberinganddatamergeinterplay_specDataMerge.xml                     TEST-FrisbyTestATTest_pricerequestdefaults_specAddQuantityandgetPRICE.xml
TEST-FrisbyTestATTest_BCnumberinganddatamergeinterplay_specWithBarcode.xml                   TEST-FrisbyTestATTest_pricerequestdefaults_specchangetoBlank.xml
TEST-FrisbyTestATTest_BCnumberinganddatamergeinterplay_specbacktoSequential.xml              TEST-FrisbyTestATTest_pricerequestdefaults_specchangetoFoil.xml
TEST-FrisbyTestATTest_BCnumberinganddatamergeinterplay_specstart.xml                         TEST-FrisbyTestATTest_pricerequestdefaults_specchangetoLexSaverregplus10milWhite.xml
TEST-FrisbyTestATTest_Barcode_specBacktoWithBarcode.xml                                      TEST-FrisbyTestATTest_pricerequestdefaults_specchangetoNumberOnly.xml
TEST-FrisbyTestATTest_Barcode_specBarcodeBlank.xml                                           TEST-FrisbyTestATTest_pricerequestdefaults_specchangetoPolyWhite.xml
TEST-FrisbyTestATTest_Barcode_specBarcodeNumberOnly.xml                                      TEST-FrisbyTestATTest_pricerequestdefaults_specchangetoVinylDestructible.xml
TEST-FrisbyTestATTest_Barcode_specstart.xml                                                  TEST-FrisbyTestATTest_pricerequestdefaults_specstart.xml
TEST-FrisbyTestATTest_CustomDesign_specChooseCustomAssetTagandverifymaterialisunselected.xml TEST-FrisbyTestATTest_pricerequestmessingwithnumbering_specAddQuantitygetPRICE.xml
TEST-FrisbyTestATTest_CustomDesign_specChoosemetal.xml                                       TEST-FrisbyTestATTest_pricerequestmessingwithnumbering_specchangetoDataMerge.xml
TEST-FrisbyTestATTest_CustomDesign_specCustomAssetTagDesignselect.xml                        TEST-FrisbyTestATTest_pricerequestmessingwithnumbering_specchangetoNumberOnly.xml
TEST-FrisbyTestATTest_CustomDesign_specSwitchbacktoSmallAssetTag.xml                         TEST-FrisbyTestATTest_pricerequestmessingwithnumbering_specchangetoSequential.xml
TEST-FrisbyTestATTest_CustomDesign_specstart.xml                                             TEST-FrisbyTestATTest_pricerequestmessingwithnumbering_specstart.xml
TEST-FrisbyTestATTest_Designsmalltocustomandback_specBacktoSmallAssetTagDesign.xml           TEST-FrisbyTestATTest_primal_specPrimalState.xml
TEST-FrisbyTestATTest_Designsmalltocustomandback_specCustomAssetTagDesign.xml                TEST-FrisbyTestSCTest_primal_specPrimalState.xml
TEST-FrisbyTestATTest_Designsmalltocustomandback_specstart.xml                               TEST-FrisbyTestVSTest_primal_specPrimalState.xml
TEST-FrisbyTestATTest_Laminate_specSelectmetalmaterial.xml                                   TEST-FrisbyTestWDTest_specPrimalTransition.xml
TEST-FrisbyTestATTest_Laminate_specSettingLaminate.xml                                       TEST-FrisbyTestWDTest_specSizeTransition.xml
TEST-FrisbyTestATTest_Laminate_specstart.xml                                                 TEST-FrisbyTestloginTest_specLoginTest.xml
TEST-FrisbyTestATTest_Logo_specAddLogo.xml                                                   TEST-FrisbyTestrequestprice.xml
jeff.l@Jeffs-MacBook-Pro:~/tests/TestReportServer (master *=)$ 
```

**Comment by lukejpreston** [comment]
The api has changed
Could you try the following please?
junit-viewer --results=static/frisby/reports/release --save=static/frisby/reports/release/results.html
The reason for the change is that you can now specify a file or a folder and results are you test results

**Comment by lukejpreston** [comment]
If this fixes your issue then please close

**Comment by JeffML** [comment]
That was it, thanks.
